theme: jekyll-theme-architect
title: SmarBina Caller ID
description: Bina Inteligente para uso didático e comercial em projetos de callcenter e telefonia.
tags: [Bina, Caller ID, Telefonia, Telefonia Fixa com Arduino, Didatico, Estudos, pcb, esquematico, lista de componentes]
